# Generated by Django 6.0.6 on 2026-06-27 13:04

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_broker',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
