# Generated by Django 6.0.6 on 2026-06-29 07:36

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_patient',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
