# Generated by Django 6.0.6 on 2026-06-30 06:02

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sos_employee',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
