# Generated by Django 6.0.6 on 2026-07-02 06:35

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_manager',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
