# Generated by Django 6.0.7 on 2026-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=50)),
                ('hod_name', models.CharField(max_length=50)),
                ('total_faculty', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_department',
            },
        ),
    ]
