# Generated by Django 6.0.7 on 2026-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_id', models.IntegerField()),
                ('scholarship_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('eligibility', models.CharField(max_length=50)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sos_scholarship',
            },
        ),
    ]
