# Generated by Django 6.0.7 on 2026-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField()),
                ('policy_holder_name', models.CharField(max_length=50)),
                ('policy_type', models.CharField(max_length=50)),
                ('premium_amount', models.IntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sos_insurance',
            },
        ),
    ]
