# Generated by Django 6.0.7 on 2026-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.CharField(max_length=50)),
                ('passing_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_exam',
            },
        ),
    ]
