# Generated by Django 6.0.7 on 2026-07-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'SOS_ROLE',
            },
        ),
    ]
