# Generated by Django 6.0.7 on 2026-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_vendor',
            },
        ),
    ]
