# Generated by Django 6.0.7 on 2026-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField()),
                ('library_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('total_books', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_library',
            },
        ),
    ]
