# Generated by Django 6.0.7 on 2026-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('contact_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_hotel',
            },
        ),
    ]
