# Generated by Django 6.0.7 on 2026-08-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_payment',
            },
        ),
    ]
