# Generated by Django 6.0.7 on 2026-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
