# Generated by Django 6.0.7 on 2026-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField()),
                ('complaint_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('complaint_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_complaint',
            },
        ),
    ]
