# Generated by Django 6.0.7 on 2026-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('contact_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_doctor',
            },
        ),
    ]
