# Generated by Django 6.0.7 on 2026-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_bank_account',
            },
        ),
    ]
