# Generated by Django 6.0.7 on 2026-09-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_room',
            },
        ),
    ]
